### ISSUE TITLE
i c u

### ISSUE THREAD

**Issue by johnfn** [ptpham/ld34#1]

**Comment by ptpham** [comment]
Grant we will beat you. O__O
...
Maybe.

**Comment by johnfn** [comment]
I'm using Javascript too (well, TypeScript). THIS WAS A MISTAKE I HATE THIS LANGUAGE

**Comment by ptpham** [comment]
JAVASCRIPT LOVES YOU PASSIONATELY

**Comment by johnfn** [comment]
NO IT DOESNT PETER. JAVASCRIPT ONLY LIKES ME AS A FRIEND. She keeps trying to set me up with her sister "undefined is not a function"

**Comment by ptpham** [comment]
You know, maybe her sister would be nicer to you if you just stopped calling her with every problem you have.

**Comment by ptpham** [comment]
#3dayoldsnark

**Comment by johnfn** [comment]
She just needs to apply herself, Peter. I've gotten into a whole array of arguments with her about this.

**Comment by ptpham** [comment]
Well, if you were a bit more partial towards her, maybe you could curry her favor.
